/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  collections: {
    users: User;
    media: Media;
    sponsees: Sponsee;
    sponsors: Sponsor;
    gallery: Gallery;
    projects: Project;
    'projects-status': ProjectsStatus;
    'grade-reports': GradeReport;
    'donation-collection': DonationCollection;
    'donation-distribution': DonationDistribution;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  db: {
    defaultIDType: number;
  };
  globals: {};
  locale: null;
  user: User & {
    collection: 'users';
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  prefix?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sponsees".
 */
export interface Sponsee {
  id: number;
  FullName: string;
  DateOfBirth?: string | null;
  Gender?: ('male' | 'female' | 'other') | null;
  Location?: string | null;
  JoinedSponsorshipProgram?: string | null;
  Family?: string | null;
  Grade?: number | null;
  Education?: string | null;
  Aspiration?: string | null;
  Hobby?: string | null;
  ProfilePicture?: (number | null) | Media;
  Gallery?: (number | null) | Gallery;
  About?: string | null;
  HowSponsorshipWillHelp?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "gallery".
 */
export interface Gallery {
  id: number;
  name: string;
  description?: string | null;
  sponsee: number | Sponsee;
  media?:
    | {
        mediaType?: ('image' | 'video') | null;
        image?: (number | null) | Media;
        video?: (number | null) | Media;
        caption?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sponsors".
 */
export interface Sponsor {
  id: number;
  firstName: string;
  lastName: string;
  email?: string | null;
  address?: string | null;
  city?: string | null;
  postalCode?: string | null;
  country?: string | null;
  region?: string | null;
  phone?: string | null;
  sponsee?: (number | Sponsee)[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects".
 */
export interface Project {
  id: number;
  ProjectTitle: string;
  ProjectType:
    | 'Children and Youth Center'
    | 'Feeding Program'
    | 'Education and Mentorship'
    | 'Electricity and Water Installation'
    | 'Other';
  Goal?: string | null;
  Impact?: string | null;
  ProjectProfilePicture?: (number | null) | Media;
  Documents?:
    | {
        document?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects-status".
 */
export interface ProjectsStatus {
  id: number;
  ProjectTitle: number | Project;
  Description: string;
  Progress: 'Started' | 'In Progress' | 'Completed' | 'Other';
  UpdatedBy?: string | null;
  LastUpdatedDate?: string | null;
  ProjectStatusProfilePicture?: (number | null) | Media;
  Documents?:
    | {
        document?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "grade-reports".
 */
export interface GradeReport {
  id: number;
  ChildName: number | Sponsee;
  AcademicYear: number;
  Semester: '1' | '2';
  MathsScore?: number | null;
  AmharicScore?: number | null;
  EnglishScore?: number | null;
  ScienceScore?: number | null;
  GamoScore?: number | null;
  Rank: number;
  AcademicProgressNote?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "donation-collection".
 */
export interface DonationCollection {
  id: number;
  SponsorName: number | Sponsor;
  DonationAmount: number;
  DonationType:
    | 'Monthly Donation'
    | 'Yearly Donation'
    | 'Youth Center'
    | 'Special Gift'
    | 'General'
    | 'Admin Cost Cover'
    | 'Other';
  Description?: string | null;
  DonationDate?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "donation-distribution".
 */
export interface DonationDistribution {
  id: number;
  SponseeName: number | Sponsee;
  DonationGivenAmount: number;
  DistributionType: 'Monthly Donation' | 'Special Gift' | 'Medical' | 'Other';
  Description?: string | null;
  DonationGivenDate?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'sponsees';
        value: number | Sponsee;
      } | null)
    | ({
        relationTo: 'sponsors';
        value: number | Sponsor;
      } | null)
    | ({
        relationTo: 'gallery';
        value: number | Gallery;
      } | null)
    | ({
        relationTo: 'projects';
        value: number | Project;
      } | null)
    | ({
        relationTo: 'projects-status';
        value: number | ProjectsStatus;
      } | null)
    | ({
        relationTo: 'grade-reports';
        value: number | GradeReport;
      } | null)
    | ({
        relationTo: 'donation-collection';
        value: number | DonationCollection;
      } | null)
    | ({
        relationTo: 'donation-distribution';
        value: number | DonationDistribution;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}